refactor: add env variable for api base url and fix naming

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,7 +29,7 @@ jobs:
       - name: 'Install dependencies'
         run: pnpm install
 
-      - name: 'Check for GitHub secret access'
+      - name: 'Check if CodebaseKB API key is set'
         run: |
           if [ -z "${{ secrets.CODEBASE_KB_API_KEY }}" ]; then
             echo "Required secret CODEBASE_KB_API_KEY is not set."
@@ -38,13 +38,17 @@ jobs:
             echo "Secret CODEBASE_KB_API_KEY is set. Proceeding with workflow."
           fi
 
+      - name: 'Check if CodebaseKB API key is set'
+        run: |
+          if [ -z "${{ secrets.BASE_API_URL }}" ]; then
+            echo "Required secret BASE_API_URL is not set."
+            exit 1
+          else
+            echo "Secret CODEBASE_KB_API_KEY is set. Proceeding with workflow."
+          fi
+
       - name: 'Build'
         run: pnpm build
-
-      - name: 'Check for deleted files'
-        env: 
-          CODEBASE_KB_API_KEY: ${{ secrets.CODEBASE_KB_API_KEY }}
-        run: node dist/scripts/checkDeletedFile.js
         
       - name: 'Rebuild README.md'
         run: 'node dist/scripts/buildReadme.js'
@@ -80,7 +84,14 @@ jobs:
         run: |
           git push origin main
 
-      - name: 'Run getSnippet.js script'
+      - name: 'Upload markdown metadata to db'
         env: 
           CODEBASE_KB_API_KEY: ${{ secrets.CODEBASE_KB_API_KEY }}
+          BASE_API_URL: ${{ secrets.BASE_API_URL }}
         run: node dist/scripts/getSnippet.js
+
+      - name: 'Check and sync deleted files to db'
+        env: 
+          CODEBASE_KB_API_KEY: ${{ secrets.CODEBASE_KB_API_KEY }}
+          BASE_API_URL: ${{ secrets.BASE_API_URL }}
+        run: node dist/scripts/syncDeletedFiles.js
